version: '3'

services:
  roome-app:
    container_name: roome
    build: ./roome
    ports:
      - "8088:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
