version: '3'

services:
  roome-app:
    container_name: roome-dev
    build: ./roome
    ports:
      - "8088:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    restart: on-failure

  redis:
    image: redis:latest
    container_name: my-redis-dev
    ports:
      - "6378:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
